feat: 닉네임 중복검사기능 추가 및 코드리펙토링
ddip-company/ddip pull request #29
Opened 2023-04-24 14:01 UTC by TAETAEMO

닉네임 중복검사기능을 추가하였습니다.

![IMG_8917](https://user-images.githubusercontent.com/104331117/234018096-6a5aeb5e-a8b3-47c6-a83d-acd39bc75c58.JPG)

닉네임을 입력한 후 중복 버튼을 누르면 사용가능한지 중복되는지 위와 같이 확인이 됩니다.

2023-05-01 05:56 UTC, soob-forest requested changes

2023-05-01 05:56 UTC, soob-forest commented on client/src/pages/SignupPage.jsx
> +  const [닉네임확인메세지, set닉네임확인메세지] = useState(null);
갑자기 변수명 한글로 쓰는 이유가 있나요

2023-05-01 05:56 UTC, soob-forest commented on client/src/pages/SignupPage.jsx
> +    // console.log(data);
주석 제거랑 콘솔로그 정리를 한 번 해야할거같네요

2023-05-01 05:56 UTC, soob-forest commented on client/src/component/LogoutButton.jsx
> +    <div className="NavLink">
className을 NavLink 이런식으로 지으면, 어떤 역할을 하는 컨포넌트인지 알 수 없어서 좋지않아 보입니다.

그리고  id를 쓰는게 더 좋지 않나요 className 보다

2023-05-03 03:33 UTC, TAETAEMO commented on client/src/pages/SignupPage.jsx
> +  const [닉네임확인메세지, set닉네임확인메세지] = useState(null);
처음에 만들때 헷갈려서 한글로 임시로 썼습니다. 바꾼거 다시 pr할게요.

2023-05-03 03:34 UTC, TAETAEMO commented on client/src/pages/SignupPage.jsx
> +    // console.log(data);
확인했습니다.

2023-05-03 03:34 UTC, TAETAEMO commented on client/src/component/LogoutButton.jsx
> +    <div className="NavLink">
아직 디자인이 안나와서 임시입니다. css시작하면 다 바꿔야합니다.

2023-05-04 16:17 UTC, merged